### ISSUE TITLE
./stream_f.exe 执行报错

### ISSUE THREAD

**Issue by paulthomas100199** [jeffhammond/STREAM#5]
![image](https://user-images.githubusercontent.com/47093973/177520968-0313cce7-ed8b-4ca0-bdba-6058114771d1.png)

**Comment by loong-C** [comment]
还想问下，这里生成的文件可以针对平台适配吗？在linux平台不在叫xx.exe文件

**Comment by loong-C** [comment]
> > I also want to ask, can the files generated here be adapted to the platform? The xx.exe file is no longer called on the linux platform
> 
> Linux doesn't care about the file suffix, so `.exe` is fine. That it complies with the Windows convention is irrelevant.

OK

**Comment by jeffhammond** [comment]
You appear to have ignored this:
> Compile with `-fmax-stack-var-size=1024` (or some other small-ish number) or run with `ulimit -s unlimited`.

Please try again.
