### ISSUE TITLE
Error compiling on GCC10.3.0

### ISSUE THREAD

**Issue by leedykop** [jeffhammond/STREAM#6]
[root@openeuler STREAM-master]# gcc -fopenmp  -DSTREAM_ARRAY_SIZE=800000000 -DNTIMES=20 -mcmodel=large stream.c -o stream_c.exe
/usr/local/gcc-10.3.0/lib/gcc/aarch64-linux/10.3.0/libgcc.a(lse-init.o): in function `init_have_lse_atomics':
/home/perfagent-plus/install_gcc/gcc-10.3.0/aarch64-linux/libgcc/../.././libgcc/config/aarch64/lse-init.c:45:(.text.startup+0x14): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against `.bss'
/usr/local/gcc-10.3.0/lib/gcc/aarch64-linux/10.3.0/libgcc.a(ldadd_4_1.o): in function `__aarch64_ldadd4_relax':
/home/perfagent-plus/install_gcc/gcc-10.3.0/aarch64-linux/libgcc/../.././libgcc/config/aarch64/lse.S:266:(.text+0x4): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `__aarch64_have_lse_atomics' defined in .bss section in /usr/local/gcc-10.3.0/lib/gcc/aarch64-linux/10.3.0/libgcc.a(lse-init.o)

If I reduce the arrary size less then 100000000, it can compile successful,but the results can't be trusted.
How to solve this problem?

**Comment by jeffhammond** [comment]
This has nothing to do with STREAM but here are some workarounds:

1. Use Clang like this:
```
clang -O2 -fopenmp -DSTREAM_ARRAY_SIZE=800000000 -DNTIMES=20  stream.c  -o stream_c.exe -mcmodel=large -L/usr/lib/llvm-9/lib
```

2. Use GCC 9 like this:
```
gcc-9 -O2 -fopenmp -DSTREAM_ARRAY_SIZE=800000000 -DNTIMES=20  stream.c  -o stream_c.exe -mcmodel=large -fno-PIC
```

3. Use GCC 10 like this:
```
gcc-10 -O2 -fopenmp -DSTREAM_ARRAY_SIZE=800000000 -DNTIMES=20  stream.c  -o stream_c.exe -mcmodel=large -fno-PIC  -mno-outline-atomics
```

With GCC, you need `-fno-PIC` to use `-mcmodel=large`.  I don't know why, but https://lists.infradead.org/pipermail/kexec/2018-January/019722.html confirms it.

You need `-mno-outline-atomics` with GCC 10 to mitigate the following issue, at least on ARM targets where LSE can be generated.
```
/usr/lib/gcc/aarch64-linux-gnu/10/libgcc.a(lse-init.o): in function `init_have_lse_atomics':
(.text.startup+0x14): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against `.bss'
/usr/lib/gcc/aarch64-linux-gnu/10/libgcc.a(ldadd_4_1.o): in function `__aarch64_ldadd4_relax':
(.text+0x4): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against symbol `__aarch64_have_lse_atomics' defined in .bss section in /usr/lib/gcc/aarch64-linux-gnu/10/libgcc.a(lse-init.o)
```
